### ISSUE TITLE
Windows App Crash

### ISSUE THREAD

**Issue by regnete** [sitewaerts/cordova-plugin-zip#3]
Mit der aktuellen Version des Plugins stürzt die cleverdox App beim ersten Versuch ein Archiv zu entpacken kommentarlos ab.

```
Name der fehlerhaften Anwendung: wwahost.exe, Version: 10.0.19041.789, Zeitstempel: 0x9bbd7506
Name des fehlerhaften Moduls: ucrtbase.dll, Version: 10.0.19041.789, Zeitstempel: 0x2bd748bf
Ausnahmecode: 0xc0000409
Fehleroffset: 0x0000000000071208
ID des fehlerhaften Prozesses: 0x7774
Startzeit der fehlerhaften Anwendung: 0x01d768fbcf90d81e
Pfad der fehlerhaften Anwendung: C:\WINDOWS\system32\wwahost.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\ucrtbase.dll
Berichtskennung: dcabd055-15db-47ba-b38a-9003a0a72923
Vollständiger Name des fehlerhaften Pakets: de.cleverdox.hoppecke.staging_2.0.9.0_x64__f9r2e6mhwyp08
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: de.cleverdox.hoppecke.staging
```
```
Fehlerbucket 1227403858428221381, Typ 5
Ereignisname: MoBEX
Antwort: Nicht verfügbar
CAB-Datei-ID: 0

Problemsignatur:
P1: de.cleverdox.hoppecke.staging_2.0.8.0_x64__f9r2e6mhwyp08
P2: praid:de.cleverdox.hoppecke.staging
P3: 10.0.19041.789
P4: 9bbd7506
P5: ucrtbase.dll
P6: 10.0.19041.789
P7: 2bd748bf
P8: 0000000000071208
P9: c0000409
P10: 0000000000000005

Angefügte Dateien:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER93E3.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER95C8.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER95E8.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER95F6.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9635.tmp.txt

Diese Dateien befinden sich möglicherweise hier:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_de.cleverdox.hop_c8766de3b3fcbee3a43b566ce315a544103e57_d62d62a5_54b87f50-38e3-42fa-9ef3-91f113e0aad2

Analysesymbol: 
Es wird erneut nach einer Lösung gesucht: 0
Berichts-ID: 9874bff2-6e51-45dc-af2c-ef8cc8259e78
Berichtstatus: 268435456
Bucket mit Hash: 3487f29260dbf7d381089d4e618ed7c5

```

[Report.wer.txt](https://github.com/sitewaerts/cordova-plugin-zip/files/6709600/Report.wer.txt)

**Comment by regnete** [comment]
Test-App stürzt auch ab.

**Comment by ChrisBase** [comment]
[ZipComponentUWP_x64_Debug.zip](https://github.com/sitewaerts/cordova-plugin-zip/files/6710193/ZipComponentUWP_x64_Debug.zip)

**Comment by ChrisBase** [comment]
[ZipComponentUWP_x64_Debug_ObjectFiles.zip](https://github.com/sitewaerts/cordova-plugin-zip/files/6710273/ZipComponentUWP_x64_Debug_ObjectFiles.zip)

**Comment by regnete** [comment]
@ChrisBase Der Fehler tritt nun in einer App die ich heute frisch erstellt habe wieder auf...

Ich binde das Plugin wie immer direkt über die Git-Url ein, damit müsste ich auf jeden Fall die Latest-Version erhalten.

Es hat ja mal funktioniert. Liegt die Ursache vielleicht darin, dass du die Release in Github erstellt hast?

```
Fehlerbucket 1489584959867723553, Typ 5
Ereignisname: MoBEX
Antwort: Nicht verfügbar
CAB-Datei-ID: 0

Problemsignatur:
P1: de.cleverdox.drop_2.0.1.0_x64__88dpwb64d4y3y
P2: praid:de.cleverdox.drop
P3: 10.0.19041.789
P4: 9bbd7506
P5: ucrtbase.dll
P6: 10.0.19041.789
P7: 2bd748bf
P8: 0000000000071208
P9: c0000409
P10: 0000000000000005

Angefügte Dateien:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDF2F.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE03A.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE04A.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE05A.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE07A.tmp.txt

Diese Dateien befinden sich möglicherweise hier:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_de.cleverdox.dro_e995e37085be6c19db6ada1b1df3c121243eaf7_ba665b0c_7ab8987d-3a4a-450f-820f-e3307adebb97

Analysesymbol: 
Es wird erneut nach einer Lösung gesucht: 0
Berichts-ID: edd6475f-f98d-4da3-8fff-ef1a815522fe
Berichtstatus: 268435456
Bucket mit Hash: bed9fb5060a0e90504ac11a0fbae1f21
CAB-Datei-Guid: 0
```

```
Name der fehlerhaften Anwendung: wwahost.exe, Version: 10.0.19041.789, Zeitstempel: 0x9bbd7506
Name des fehlerhaften Moduls: ucrtbase.dll, Version: 10.0.19041.789, Zeitstempel: 0x2bd748bf
Ausnahmecode: 0xc0000409
Fehleroffset: 0x0000000000071208
ID des fehlerhaften Prozesses: 0x2e8c
Startzeit der fehlerhaften Anwendung: 0x01d77884bf118216
Pfad der fehlerhaften Anwendung: C:\WINDOWS\system32\wwahost.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\ucrtbase.dll
Berichtskennung: edd6475f-f98d-4da3-8fff-ef1a815522fe
Vollständiger Name des fehlerhaften Pakets: de.cleverdox.drop_2.0.1.0_x64__88dpwb64d4y3y
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: de.cleverdox.drop
```

**Comment by regnete** [comment]
Fehler tritt auch auf, wenn ich auf Version 3.1.2 zurück gehe. Die enthält deinen Code nicht. Also evtl. andere Ursache?

**Comment by regnete** [comment]
Es scheint doch etwas mit ZipComponentUWP.dll zu tun zu haben.

![image](https://user-images.githubusercontent.com/3276866/125617329-0400e8ff-b759-459f-abb2-4ab94c6f9042.png)
![image](https://user-images.githubusercontent.com/3276866/125617399-54efa502-b148-4176-a065-38779dfa2326.png)

**Comment by ChrisBase** [comment]
Ich schaue mir das jetzt an und lasse dich wissen, was ich finde.
Würde unabhängig davon vorschlagen dass ich miniz-cpp als Standard festlege.
Das sind nur ca. 10% Performance-Verlust, aber eine stabilere Implementierung.

**Comment by regnete** [comment]
ok

**Comment by regnete** [comment]
miniz-cpp als Standard macht in jedem Fall Sinn. Unsere Zipfiles beinhalten meist viele kleinen Dateien, und hat miniz-cpp die Nase vorn. Wenn es dann auch noch stabiler ist gewinnt es das Rennen.

**Comment by regnete** [comment]
Wenn ich auf die alte Version 3.1.2 des Plugins zurückgehe, stürzt die App nicht ab. Es liegt also definitiv am Zip-Plugin.

**Comment by regnete** [comment]
Nach deiner Umstellung auf miniz-cpp stürzt die App zumindest nicht mehr ab. Es scheint tatsächlich ein Problem mit den Zip-Files zu sein ...

**Comment by ChrisBase** [comment]
Ein paar Infos zur aktuellen Version.

Die Abstraktionsschicht der Zip-Algorithmen fängt nun alle Exceptions ab, um Abstürze zu vermeiden. Bei Exceptions geben die Methoden Fehler zurück und in JavaScript wird der Fehler in der Konsole ausgegeben. Ich habe auch geprüft, dass die Fehler-Callbacks aufgerufen werden und bei korrupten Zip-Dateien die App nicht abstürzt.

Die UWP-Komponente hat nun eine Versionsnummer, die ich auch in der Konsole ausgegeben wird, damit wir immer sicher wissen, welche in Verwendung ist.

Bei Zip-Archiven mit vielen kleinen Dateien (z.B. user-main.package.zip: 7338 Dateien, ca. 26MB entpackt) geht ein Teil der Performance durch die Kommunikation von JavaScript, dessen Callbacks und dem Marshalling in nativen Code, verloren. Die native Test-App braucht für user-main.package.zip mit miniz-cpp nur 800ms! In der Cordova-Sample-App aber 2200ms.
Zum Teil werden Dateien so schnell entpackt, dass die Progress-Callbacks (über 7000 innerhalb von etwa 3 Sekunden) die Event-Queue fluten.
In meinen Sample-App-Tests sehe ich nur, das er begonnen hat, und das er fertig wurde.

Bzgl. des andyzip-Problems:
Alle im fis.zip Archiv enthaltenen Archive konnte ich fehlerfrei entpacken.
Wenn du noch andere Dateien verarbeitet hast, und es Dir nichts ausmacht, sie mir zukommen zu lassen, könnte ich auch das prüfen. Ansonsten wäre es auch interessant zu wissen, was bei Dir passiert, wenn du mit der aktuellen Version auf andyzip schaltest.
Können das aber auch gerne dabei belassen, wenn die aktuelle Lösung zufriedenstellend ist.

**Comment by regnete** [comment]
Mit miniz-cpp wird nun einen einzige Datei als Output für alle Dateien des Archivs verwendete. Alle Inhalte werden immer an diese Datei angehängt, Unterverzeichnisse werden nicht angelegt.

**Comment by ChrisBase** [comment]
Ja, ein wirklich böser Fehler...
Und es ließ mir keine Ruhe, warum das bei mir nicht auftrat, obwohl ich mit unterschiedlichsten Archiven getestet habe. Aber nach längerer Suche habe ich festgestellt, das Cordova lokale Plugins nicht in die sample-app kopiert, wenn man z.B. die Visual Studio Solution noch offen hat, was bei mir während der Entwicklung öfters der Fall war.
Zum Testen habe ich immer mit `app_create.sh && app_prepare.sh && app_run.sh` aktualisiert und im Output nur den Erfolg der letzten Skripte gesehen, da app_create.sh auch im Fehlerfall exitcode 0 ausgab.
Somit habe ich wohl einige Tests mit älteren Builds gemacht, ohne es zu merken.
Damit das nicht mehr passieren kann legt app_create.sh nun immer frische build-Ordner an, und prüft zusätzlich ob `cordova platform add` erfolgreich war. Schlägt letzteres fehl, so bricht das Skript mit einer deutlichen Fehlermeldung ab, und setzt auch den exitcode auf 1.

Folgende Punkte sind mir noch aufgefallen:

1. Seit dem app_create.sh kein CORDOVA_VERSION mehr setzt, wird bei dessen Aufruf folgendes ausgegeben:
`Plugin doesn't support this project's cordova-windows version.
cordova-windows: 7.0.1, failed version requirement: <=5.0.0
Skipping 'cordova-plugin-console' for windows`
Die App läuft aber trotzdem. Wird cordova-plugin-console evtl. gar nicht gebraucht?
2. jszip legt als einziger Zip-Algorithmus keine leeren Verzeichnisse an, falls es welche im Archiv gibt
Falls das so bleiben kann, könnten wir es zumindest in der README.md erwähnen.

**Comment by regnete** [comment]
- Da hab ich das wohl intuitiv immer richtig gemacht: VS geschlossen wenn ich die App neu erstellt habe.
- cordova-plugin-console kann wohl raus
- Leere Verzeichnisse benötigen wir nicht. Erwähnung in README ist gut.
