### ISSUE TITLE
Windows: Cannot unzip archive with empty files

### ISSUE THREAD

**Issue by regnete** [sitewaerts/cordova-plugin-zip#4]
Sobald das Zip eine Datei mit Größe 0 enthält, wird mit Fehler abgebrochen.
Leere Dateien sind aber zulässig. Einen Warnung auszugeben wäre sinnvoll, aber es ist definitiv kein Fehler.

**Comment by ChrisBase** [comment]
Behoben in [v3.2.3](https://github.com/sitewaerts/cordova-plugin-zip/releases/tag/v3.2.3)
