### ISSUE TITLE
v3.2.3 funktioniert nicht

### ISSUE THREAD

**Issue by regnete** [sitewaerts/cordova-plugin-zip#5]
In der cleverdox App wird kein Zip mehr korrekt entpackt.

![image](https://user-images.githubusercontent.com/3276866/145961118-7bbd146b-b264-4290-93d8-7d25691e21fe.png)

**Comment by ChrisBase** [comment]
Gefixt in [v.3.2.4](https://github.com/sitewaerts/cordova-plugin-zip/commit/19c18aad4dfa62dee7993e8d125fa1670ccfcf22).
