### ISSUE TITLE
Sicherheitslücke beim Pfaddurchlauf

### ISSUE THREAD

**Issue by regnete** [sitewaerts/cordova-plugin-zip#6]
Unsere App wird von Google abgelehnt:
![image](https://user-images.githubusercontent.com/3276866/192967606-9fd6711b-2650-454a-a758-1c56b6475419.png)
siehe auch https://support.google.com/faqs/answer/9294009
@ChrisBase: Kannst du das bitte fixen?

**Comment by ChrisBase** [comment]
Wird heute erledigt.
